---
# This is a simple playbook with two plays
- name: first play
  hosts: host01
  tasks:
    - name: first task
      yum:
        name: httpd
        status: present
    - name: second task
      service:
        name: httpd
        enabled: true

- name: second play
  hosts: host02
  tasks:
    - name: first task
	  service:
	    name: mariadb
	    enabled: true