---
- hosts: host01
  tasks:
  - name: Check if PHP is installed
    command: php -v
    register: php_installed
    ignore_errors: true

  - name: This task is only executed if PHP is installed
    debug: var=php_installed
    when: php_installed.rc == 0

  - name: This task is only executed if PHP is NOT installed
    debug: msg='PHP is NOT installed'
    when: php_installed.rc != 0
