---
- hosts: host01
  tasks:
  - name: populate service facts
    service_facts:

  - debug:
      var: ansible_facts.services["httpd.service"].state
  - name: Check that you can connect (GET) to host01
    uri:
      url: http://host01
    when: ansible_facts.services["httpd.service"].state == "running"
