# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |rs|
    rs.memory = 2048
    rs.cpus = 2
  end

  # Will not check for box updates during every startup.
  config.vm.box_check_update = false


  # Master node where ansible will be installed
  config.vm.define "master01" do |master01|
    master01.vm.box = "centos/7"
    master01.vm.hostname = "master01.anslab.com"
    master01.vm.network "private_network", ip: "10.20.30.10"
    master01.vm.provision "shell", path: "bootstrap.sh"
    master01.vm.provision "file", source: "key_gen.sh", destination: "/home/vagrant/"
  end

  # Managed node 1.
  config.vm.define "m1" do |m1|
    m1.vm.box = "centos/7"
    m1.vm.hostname = "host01.anslab.com"
    m1.vm.network "private_network", ip: "10.20.30.11"
    m1.vm.provision "shell", path: "bootstrap.sh"
  end

  # Managed node 2.
  config.vm.define "m2" do |m2|
    m2.vm.box = "centos/7"
    m2.vm.hostname = "host02.anslab.com"
    m2.vm.network "private_network", ip: "10.20.30.12"
    m2.vm.provision "shell", path: "bootstrap.sh"
  end
  
    # Managed node 3.
  config.vm.define "m3" do |m3|
    m3.vm.box = "centos/7"
    m3.vm.hostname = "host03.anslab.com"
    m3.vm.network "private_network", ip: "10.20.30.13"
    m3.vm.provision "shell", path: "bootstrap.sh"
  end

end
